# src/AudiovisualesBundle/Resources/config/validation.yml

AudiovisualesBundle\Entity\Solicitud:
  properties:
    desde:
      - GreaterThanOrEqual: today
    hasta:
      - GreaterThanOrEqual: today