<?php

namespace AudiovisualesBundle\Repository;

/**
 * DatosFacturacinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosFacturacinRepository extends \Doctrine\ORM\EntityRepository
{
}
