<?php

namespace FormularioBundle\Repository;

/**
 * CalculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalculoRepository extends \Doctrine\ORM\EntityRepository
{
}
