<?php

namespace FormularioBundle\Repository;

/**
 * DatosSolEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosSolEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
