<?php

namespace FormularioBundle\Repository;

/**
 * FacturacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturacionRepository extends \Doctrine\ORM\EntityRepository
{
}
