<?php

namespace FormularioBundle\Repository;

/**
 * ServiciosSolicitadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiciosSolicitadosRepository extends \Doctrine\ORM\EntityRepository
{
}
