<?php

namespace FormularioBundle\Repository;

/**
 * SolicitanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitanteRepository extends \Doctrine\ORM\EntityRepository
{
}
