<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNenmck3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNenmck3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNenmck3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNenmck3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNenmck3\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Nenmck3',
    'container.build_id' => 'df1aabd7',
    'container.build_time' => 1523286926,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNenmck3');
